# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-24 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arch',
            name='image',
            field=models.CharField(default='default.jpg', max_length=255),
            preserve_default=False,
        ),
    ]
